import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  parentStyle: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
    alignItems: "center",
  },
  emojiWithTextInputStyle: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    borderRadius: 30,
    flex: 1,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginRight: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  textInputStyle: {
    flex: 1,
    fontSize: 16,
    color: "#333",
    marginLeft: 10,
  },
  cameraWithMicAndSendButtonStyle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sendButton: {
    backgroundColor: "#4CAF50",
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  sendTextStyle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  senderMessageStyle: {
    alignSelf: "flex-end",
    backgroundColor: "#A3E4D7",
    padding: 12,
    borderRadius: 18,
    borderBottomRightRadius: 5,
    marginVertical: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  receiverMessageStyle: {
    alignSelf: "flex-start",
    backgroundColor: "#F3F4F6",
    padding: 12,
    borderRadius: 18,
    borderBottomLeftRadius: 5,
    marginVertical: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  messageText: {
    fontSize: 16,
    color: "#333",
  },
  messageTimeStyle: {
    marginTop: 5,
    fontSize: 12,
    color: "#888",
    textAlign: "right",
  },
  nameStyle: {
    fontWeight: "600",
    fontSize: 14,
    color: "#555",
    marginBottom: 5,
  },
  imageStyle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
  },
  headerStyle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  groupDetailsStyle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#000",
  },
  emojiSelector: {
    height: 250,
    borderTopWidth: 1,
    borderColor: "#E0E0E0",
  },
  // Additional styling for images sent in the chat
  imageMessageStyle: {
    width: 200,
    height: 200,
    borderRadius: 15,
    marginTop: 5,
  },
  // Styling for an empty state
  emptyStateContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  emptyStateText: {
    fontSize: 16,
    color: "#888",
    textAlign: "center",
    paddingHorizontal: 20,
  },
});

export default styles;
