const jobs = [
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile Developer",
    "Data Scientist",
    "UI/UX Designer",
    "DevOps Engineer",
    "Product Manager",
    "Software Engineer",
    "Database Administrator",
    "Cybersecurity Analyst",
    "Machine Learning Engineer",
    "Artificial Intelligence Engineer",
    "Blockchain Developer",
    "Cloud Solutions Architect",
    "Technical Support Specialist",
    "IT Consultant",
    "System Administrator",
    "Network Engineer",
    "IT Project Manager",
    "IT Business Analyst",
    "QA Engineer",
    "Test Automation Engineer",
    "Game Developer",
    "Web Developer",
    "Embedded Systems Engineer",
    "Site Reliability Engineer",
    "Big Data Engineer",
    "Data Analyst",
    "Business Intelligence Analyst",
    "ERP Consultant",
    "Help Desk Technician",
    "Information Security Manager",
    "IoT Developer",
    "Solutions Architect",
    "Software Development Manager",
    "IT Auditor",
    "IT Risk Manager",
    "CRM Specialist",
    "SEO Specialist",
    "Digital Marketing Manager",
    "Content Strategist",
    "Marketing Analyst",
    "Social Media Manager",
    "Email Marketing Specialist",
    "Growth Hacker",
    "Market Research Analyst",
    "Customer Success Manager",
    "Account Manager",
    "Sales Engineer",
    "Technical Writer",
    "E-commerce Specialist",
    "HR Specialist",
    "Recruiter",
    "Talent Acquisition Specialist",
    "Operations Manager",
    "Supply Chain Manager",
    "Logistics Coordinator",
    "Procurement Manager",
    "Financial Analyst",
    "Investment Analyst",
    "Accountant",
    "Auditor",
    "Tax Consultant",
    "Management Consultant",
    "Legal Advisor",
    "Paralegal",
    "Compliance Officer",
    "Research Scientist",
    "Lab Technician",
    "Biomedical Engineer",
    "Clinical Research Coordinator",
    "Healthcare Administrator",
    "Nurse",
    "Physician Assistant",
    "Medical Biller",
    "Pharmacist",
    "Physical Therapist",
    "Occupational Therapist",
    "Speech-Language Pathologist",
    "Teacher",
    "Instructional Designer",
    "School Counselor",
    "Education Administrator",
    "Training Specialist",
    "Customer Service Representative",
    "Retail Sales Associate",
    "Store Manager",
    "Real Estate Agent",
    "Property Manager",
    "Facilities Manager",
    "Event Planner",
    "Travel Agent",
    "Tour Guide",
    "Chef",
    "Pastry Chef",
    "Sous Chef",
    "Restaurant Manager",
    "Barista",
    "Bartender",
    "Sommelier",
    "Interior Designer",
    "Architect",
    "Civil Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Chemical Engineer",
    "Environmental Engineer",
    "Structural Engineer",
    "Aerospace Engineer",
    "Automotive Engineer",
    "Industrial Engineer",
    "Production Manager",
    "Quality Control Inspector",
    "Manufacturing Engineer",
    "Maintenance Technician",
    "Warehouse Manager",
    "Forklift Operator",
    "Machine Operator",
    "Production Planner",
    "HVAC Technician",
    "Plumber",
    "Electrician",
    "Construction Manager",
    "Site Supervisor",
    "Safety Officer",
    "Surveyor",
    "Landscaper",
    "Urban Planner",
    "Graphic Designer",
    "Illustrator",
    "Animator",
    "Motion Graphics Designer",
    "Video Editor",
    "Photographer",
    "Photo Editor",
    "Sound Engineer",
    "Music Producer",
    "Voice Actor",
    "Radio Host",
    "News Anchor",
    "Journalist",
    "Copywriter",
    "Editor",
    "Proofreader",
    "Public Relations Specialist",
    "Communications Manager",
    "Brand Manager",
    "Creative Director",
    "Art Director",
    "Fashion Designer",
    "Textile Designer",
    "Pattern Maker",
    "Jewelry Designer",
    "Accessory Designer",
    "Makeup Artist",
    "Hair Stylist",
    "Cosmetologist",
    "Esthetician",
    "Fitness Trainer",
    "Yoga Instructor",
    "Pilates Instructor",
    "Dietitian",
    "Nutritionist",
    "Personal Trainer",
    "Massage Therapist",
    "Chiropractor",
    "Acupuncturist",
    "Life Coach",
    "Career Coach",
    "Business Coach",
    "Executive Coach",
    "Carpenter",
    "Painter",
    "Sculptor",
    "Graphic Artist",
    "Tattoo Artist",
    "Furniture Maker",
    "Cabinet Maker",
    "Blacksmith",
    "Jeweler",
    "Florist",
    "Calligrapher",
    "Glassblower",
    "Ceramicist",
    "Textile Artist",
    "Metalworker",
    "Printmaker",
];

export default jobs;