const jobAndProficientList = [
    "Web Developer",
    "Graphic Designer",
    "Content Writer",
    "SEO Specialist",
    "UX/UI Designer",
    "Data Scientist",
    "Backend Developer",
    "Frontend Developer",
    "Digital Marketer",
    "Software Engineer",
    "Video Editor",
    "Copywriter",
    "Project Manager",
    "Mobile App Developer",
    "Marketing Specialist",
    "Cloud Architect",
    "Database Administrator",
    "Full Stack Developer",
    "Cybersecurity Specialist",
    "Business Analyst",
    "Carpenter",
    "Plumber",
    "Blacksmith",
    "Electrician",
    "Painter",
    "Mason",
    "Mechanic",
    "Locksmith",
    "Welder",
    "Roofer",
    "HVAC Technician",
    "Landscaper",
    "Handyman",
    "Construction Worker",
    "Pool Cleaner",
    "Pest Control Expert",
    "Floor Installer",
    "Home Inspector",
    "Tiler",
    "Builder",
    "Glazier",
    "Drywall Installer",
    "Tile Setter",
    "Concrete Finisher",
    "Demolition Specialist",
    "Insulation Installer",
    "Gardener",
    "Fence Installer",
    "Pressure Washer",
    "General Contractor",
    "Window Installer",
    "Electric Motor Specialist",
    "Elevator Mechanic",
    "Solar Panel Installer",
    "Refrigeration Technician",
    "Fireplace Installer",
    "Gutter Installer",
    "Appliance Repair Technician",
    "Potter",
    "Jeweler",
    "Tailor/Seamstress",
    "Shoemaker/Cobbler",
    "Upholsterer",
    "Glassblower",
    "Leatherworker",
    "Stone Carver/Sculptor",
    "Bookbinder",
    "Luthier",
    "Basket Weaver",
    "Cooper",
    "Thatcher",
    "Farrier",
    "Clockmaker",
    "Tanner",
    "Silversmith",
    "Weaver",
    "Knitter/Crocheter",
    "Engraver",
    "Taxidermist",
    "Sign Maker",
    "Ceramicist",
    "Rope Maker",
    "Shipwright",
    "Toymaker",
    "Furniture Maker",
    "Calligrapher",
    "Paper Maker",
    "Instrument Maker",
    "Candle Maker",
    "Soap Maker",
    "Quilter",
    "Embroidery Artist",
    "Model Maker",
    "Marble Worker",
    "Hat Maker (Milliner)",
    "Chainmail Maker",
    "Wood Carver",
    "Fabric Dyer",
    "Corset Maker",
    "Armorer",
    "Puppet Maker",
    "Stained Glass Artist",
    "Rug Maker",
    "Brewer (Craft Beer)",
    "Cheesemaker",
    "Baker (Artisanal)",
    "Candle Dipper",
    "Furniture Restorer"
  ];
  export default jobAndProficientList;