name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.17.0" 

      - name: Install dependencies and SonarQube Scanner
        run: |
          npm install
          npm install sonarqube-scanner --save-dev
        working-directory: ./Frontend/Mobile/

      - name: SonarQube Scan
        run: npm run sonar-scanner
        working-directory: ./Frontend/Mobile/
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
